#!/bin/bash

source orkhideya
ork_include media

_target_vault="$1"
! media_shelved "$_target_vault" && exit 1

_vault_ident_path="$(media_identity_path "$_target_vault")"
_vault_catacomb_path="$(media_catacomb)/raw/$_vault_ident_path"
! test -d "$_vault_catacomb_path" && exit 2
! rm -rf "$_vault_catacomb_path" && exit 3

exit 0
