#!/bin/bash

source orkhideya
ork_include media
ork_include stdlib
ork_include stdout

function pathfriendly_directory
{
    local _filename="$1"
    test -z "$_filename" && return 1

    _filename="$(echo "$_filename" | sed -r -e 's,[<>{}=@#%^&\*:;\'\"]+,,g')"
    _filename="$(echo "$_filename" | sed -r -e 's,^\s+,,' -e 's,\s$,,' -e 's,\s+,_,g')"

    echo "$_filename"
}

function pathfriendly_file
{
    local _filename="$1"
    test -z "$_filename" && return 1

    pathfriendly_directory "$_filename" | tr '[:upper:]' '[:lower:]'
    return 0
}

function pathified_first_character
{
    local _string="$1"
    test -z "$_string" && return 1

    local _first_character="$(echo ${_string:0:1} | tr '[:lower:]' '[:upper:]')"

    if [ -z "$(echo "$_first_character" | egrep -i -o '^[A-Z0-9]$')" ]; then
        echo "SYM"
    else
        echo "$_first_character"
    fi

    return 0
}

